### ISSUE TITLE
Investigate how Uber / DoorDash / Lyft protects people against random users picking them up / delivering goods

### ISSUE THREAD

**Issue by s0** [covidaidapp/covidaid#8]
This is needed for the more PIN-centric approach detailed here: https://github.com/neighborhood-assistance/info/blob/master/meetings/team_leads/2020-03-17.md

Google doc for collecting research points: https://docs.google.com/document/d/1MyT_hI4SbVieUqnkMEuhSLLsGqEUOc_bMxW54XDx8Io/edit?usp=sharing

**Comment by edmkitty** [comment]
Possible Solutions or Mitigating Factors to Implement
- Rating system
- Background checks through third parties: 
     - https://www.idnow.io/ (Germany?)
     - https://checkr.com/ (US-only)
- Authentication through third parties such as Facebook ID
